console.log("hola")
console.log(window.document)
console.log(document.head)
console.log(document.body)
console.log(document.documentElement)
console.log(document.doctype)
console.log(document.characterSet)
console.log(document.title)
console.log(document.links)
console.log(document.images)
console.log(document.forms)
console.log(document.styleSheets)
console.log(document.scripts)
setTimeout(()=>{
  console.log(document.getSelection().toString())
},3000)
//no es recomendable lo siguiente
document.write("<h2>Hola mundo desde DOM</h2>")
